### ISSUE TITLE
duplicate ClusterRole in knative-v1.12.1/eventing-kafka-post-install.yaml

### ISSUE THREAD

**Issue by fbartnitzek** [knative-extensions/eventing-kafka-broker#3533] opened 2023-12-14 13:22 UTC
**Describe the bug**

The released file [eventing-kafka-post-install.yaml](https://github.com/knative-extensions/eventing-kafka-broker/releases/download/knative-v1.12.1/eventing-kafka-post-install.yaml) contains the ClusterRole `knative-kafka-controller-post-install` twice.
Once in line 15 and another time in line 320.

Tools like the `kubectl_file_documents` data of the terraform provider `gavinbunney/kubectl` will fail with:

```
Error: duplicate manifest found with id: /apis/rbac.authorization.k8s.io/v1/clusterroles/knative-kafka-controller-post-install
```

 **Expected behavior**

All resources within the yaml-manifest are unique.

 **To Reproduce**
Steps to reproduce the behavior.

see file

 **Knative release version**

knative v1.12.1

 **Additional context**
Add any other context about the problem here such as proposed priority

**Comment by pierDipi** [comment] 2023-12-14 15:48
This is a duplicate of https://github.com/knative-extensions/eventing-kafka-broker/issues/3316, there is a PR to fix this https://github.com/knative-extensions/eventing-kafka-broker/issues/3533

**Closed** 2023-12-19 21:18 UTC
Labels: kind/bug, triage/accepted
